### ISSUE TITLE
Creation of Readme.md in your project 

### ISSUE THREAD

**Issue by Amansingh0807** [sunny7899/c-basic#1]
I will add these sections or features in your Readme file with best interface. 

- Add the Project Title: Write the project name at the top.
 
- Write a Short Project Description: Give a brief explanation of what the project is about.
 
- List the Tech Stack: Mention the technologies used in the project.

- Provide Installation Instructions: Include steps on how to clone, set up, and run the project locally.

- Write Contribution Guidelines: Specify how others can contribute to the project.

**Comment by sunny7899** [comment]
Great Go ahead @Amansingh0807
