### ISSUE TITLE
Add unit conversion code to this calculator code

### ISSUE THREAD

**Issue by SwagatRanjanBehera** [sunny7899/c-basic#18]
Add a feature to perform simple unit conversions (like meters to kilometers, Celsius to Fahrenheit, etc.). This can add a practical utility aspect to the calculator.

**Comment by SachinSihag1407** [comment]
@sunny7899 

#18

### Feature Added: Unit Conversion Utility

This pull request enhances the calculator functionality by adding a feature for simple unit conversions, catering to practical utility needs. The following conversions have been implemented:

**- **Meters to Kilometers:**** Converts distance in meters to kilometers.
**- Celsius to Fahrenheit:** Converts temperature from Celsius to Fahrenheit.
**- Kilometers to Miles:** Converts distance in kilometers to miles.
**- Fahrenheit to Celsius:** Converts temperature from Fahrenheit to Celsius.

- These additions not only expand the calculator's capabilities but also make it more versatile for everyday calculations. The user can now seamlessly perform mathematical operations alongside necessary unit conversions, making this tool more valuable and user-friendly.
