### ISSUE TITLE
Adding Tic-Tac-Toe project

### ISSUE THREAD

**Issue by Chelseasingla1** [sunny7899/c-basic#2]
For this repository, I would like to add a Tic-Tac-Toe project

**Comment by sunny7899** [comment]
@Chelseasingla1 you will create this using C?

**Comment by Chelseasingla1** [comment]
> @Chelseasingla1 you will create this using C?

@sunny7899 yes

**Comment by coderavi1612** [comment]
Hey I have made PR could you please update in main
I have created Tic Tac Toe game using C language
